name = "blog-backend"
main = "src/router.ts"
compatibility_date = "2022-10-28"
node_compat = true

[dev]
port = 8787

[vars]
BACKEND_URL = "https://blog-backend.tonydang.workers.dev"
BLOG_URL = "https://tonydang.blog"
MODE = "production"
