name = "blog-backend"
main = "src/router.ts"
compatibility_date = "2023-03-14"
minify = true
node_compat = true

[dev]
port = 8787

[vars]
BACKEND_URL = "https://blog-backend.tonydang.workers.dev"
BLOG_URL = "https://tonydang.com"
MODE = "production"
